### ISSUE TITLE
Publish to MELPA

### ISSUE THREAD

**Issue by mikavilpas** [sp3ctum/evil-lispy#10]
I'd like to offer people with an easy way of installation. Currently there is no easy, maintainable way of doing this.

Seeing as what I've done is build on your work @bcarrell, how would you feel about this? I'm open to suggestions and would like to invoke conversation :smile:

**Comment by bcarrell** [comment]
Sure, go ahead!  If you've got the time to take it further, you have my blessing to do as you wish.

**Comment by mikavilpas** [comment]
Thanks a lot for getting back! I really like your work with it.
:+1:
