### ISSUE TITLE
evil-define-state undefined

### ISSUE THREAD

**Issue by wnederhof** [sp3ctum/evil-lispy#11]
Hi there,

First off, I love evil-lispy, thanks a lot!

After installing evil-lispy, I got the following error on startup:

Error: (void-function evil-define-state)

After running emacs in debug mode, it pointed to the `evil-lispy-autoloads.el` file, which is apparently (I am no Emacs expert) autogenerated by Emacs.

After a closer inspection, I found that the `evil-define-state` function was defined in `evil-lispy.el` (using `(put 'evil-define-state 'lisp-indent-function 'defun)`), but not in the autogenerated file.

**Comment by mikavilpas** [comment]
Hi! Sorry, I must have missed this somehow. 

Do you still get this? I'll have a look at it.

**Comment by mikavilpas** [comment]
Closing this for now. Please reopen if the issue persists.
