### ISSUE TITLE
Recovering from "Scan error: Unbalanced parenthesis"?

### ISSUE THREAD

**Issue by bpstahlman** [sp3ctum/evil-lispy#13]
I have the following snippet of (pointless) scheme code:

```
(foo (foo
      43
      (+ 41 (foo 1 2
```

Evil-lispy will not allow me to close the parens at the end of the 3rd line. Can't remember how they got unbalanced, but when it gets to that state, is there a way to force a re-balancing, or perhaps force the insertion manually? More generally, what is evil-lispy's philosophy regarding balanced parens?

**Comment by mikavilpas** [comment]
Ah, I hit this case every so often too. With evil-mode, you can do `<insert-state> C-q )` to insert a literal paren.
I think lispy expects the programmer to fix these kinds of errors himself.

**Comment by bpstahlman** [comment]
Ah yes. That did it. Thanks.
Brett S.
