### ISSUE TITLE
Can't add marks to buffer

### ISSUE THREAD

**Issue by zzantares** [sp3ctum/evil-lispy#17]
Hi, I'm having trouble to find out if marks had been suppressed in favor of another `evil-lispy` feature or this is indeed a bug.

Let me explain, I tend to use a lot the marking ability from evil to save the current cursor position using `m` prefix so that latter I jump back to that place. With `evil-lispy` this does not longer works. 

Example: While in normal mode typing `ma` will result in `m a is not defined` message and the mark is not set, thus when using `'a` to jump to mark I get `Marker ‘a’ is not set in this buffer`.

I don't know if this is related to a conflict with #9, or can this functionality be achieved with lispy in a more effective way?

Thanks for the help!

**Comment by mikavilpas** [comment]
Ah, you're right. This is a bug!
I'll try to find a way to work around it.

**Comment by mikavilpas** [comment]
https://github.com/sp3ctum/evil-lispy/pull/19 changes marking from `mv` to `C-SPC` so evil-mode marks are available again.

**Comment by zzantares** [comment]
Thanks a lot!
