### ISSUE TITLE
Show available keys in a popup (hydra)

### ISSUE THREAD

**Issue by mikavilpas** [sp3ctum/evil-lispy#3]
Lispy has a ton of [keys](http://oremacs.com/lispy/). A human-readable collection of them could be nice. Lispy already has a dependency to hydras, so this could be one option.

**Comment by mikavilpas** [comment]
Could also contribute this back to lispy itself, not evil-lispy per se.

**Comment by sp3ctum** [comment]
Could also contribute this back to lispy itself, not evil-lispy per se.
